import { expand } from "dotenv-expand";
import { config } from "dotenv";
import { db } from "../index";
import * as schema from "../schema";
import { seedUsers } from "../seed/seed-users";

// Load .env, then overlay .env.test
expand(config({ path: ".env" }));
expand(config({ path: ".env.test", override: true }));

async function seedTestDatabase() {
  try {
    console.log("Setting up test database...");
    console.log(`DATABASE_URL: ${process.env.DATABASE_URL}`);

    // Push schema to test database
    console.log("Pushing schema...");
    const drizzleKit = await import("drizzle-kit/api");
    const { pushSQLiteSchema } = drizzleKit;
    const { apply } = await pushSQLiteSchema(schema, db);
    await apply();
    console.log("Schema pushed");

    // Reuse the credentials generated by db:seed; generate only if empty
    const users = await seedUsers();
    console.log(`Seeded ${users.length} test users`);

    console.log("Test database seeded successfully!");
    process.exit(0);
  } catch (error) {
    console.error("Error seeding test database:", error);
    process.exit(1);
  }
}

seedTestDatabase();
