import { randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { auth } from "../../lib/auth";
import { userSeeds, type UserSeed } from "./user.seed";

const USER_COUNT = 5;
const SEED_FILE = join(import.meta.dir, "user.seed.ts");

function randomPassword(): string {
  // base64url keeps the password to safe, form-fillable characters
  return randomBytes(18).toString("base64url");
}

function generateUsers(): UserSeed[] {
  return Array.from({ length: USER_COUNT }, (_, i) => ({
    email: `user-${i + 1}@gmail.com`,
    password: randomPassword(),
    name: `User ${i + 1}`,
    userId: "",
  }));
}

function writeSeedFile(users: UserSeed[]): void {
  const records = users
    .map(
      (user) =>
        `  {\n` +
        `    email: ${JSON.stringify(user.email)},\n` +
        `    password: ${JSON.stringify(user.password)},\n` +
        `    name: ${JSON.stringify(user.name)},\n` +
        `    userId: ${JSON.stringify(user.userId)},\n` +
        `  },`,
    )
    .join("\n");

  const content = `// Generated by \`bun run db:seed\` — do not edit by hand.
export type UserSeed = {
  email: string;
  password: string;
  name: string;
  userId: string;
};

export const userSeeds: UserSeed[] = [
${records}
];
`;

  writeFileSync(SEED_FILE, content);
}

/**
 * Create test users via Better Auth (properly hashed passwords).
 *
 * - `regenerate: true` (db:seed) always generates fresh random passwords and
 *   rewrites user.seed.ts.
 * - `regenerate: false` (seed-test) reuses the credentials already in
 *   user.seed.ts, only generating when the file is still empty.
 */
export async function seedUsers({
  regenerate,
}: {
  regenerate: boolean;
}): Promise<UserSeed[]> {
  const shouldGenerate = regenerate || userSeeds.length === 0;
  const targets = shouldGenerate ? generateUsers() : userSeeds;

  const created: UserSeed[] = [];
  for (const user of targets) {
    try {
      const result = await auth.api.signUpEmail({
        body: { email: user.email, password: user.password, name: user.name },
      });
      created.push({ ...user, userId: result?.user?.id ?? user.userId });
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : String(error);
      if (message.includes("already exists") || message.includes("duplicate")) {
        // Keep the existing credentials so the file stays in sync with the DB
        created.push(user);
      } else {
        throw error;
      }
    }
  }

  if (shouldGenerate) writeSeedFile(created);
  return created;
}
